name: CMake
on: [push]

jobs:
  build_llvm:
    runs-on: windows-latest
    env:
      LLVM_VERSION: "19.1.5"
    steps:    
      - name: Set up Visual Studio Dev Environment
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          toolset: latest
          vs-path: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools'
          
      - name: Checkout LLVM
        run: git clone --depth 1 --branch llvmorg-${{ env.LLVM_VERSION }} https://github.com/llvm/llvm-project.git
        
      - name: Configure LLVM
        run: cmake -S llvm-project/llvm -B llvm-project/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DLLVM_USE_CRT_RELEASE=MT -DLLVM_ENABLE_PROJECTS="llvm;clang;lld"

      - name: Build LLVM
        run: cmake --build llvm-project/build --config Release

      - name: Install LLVM
        run: cmake --install llvm-project/build --prefix $GITHUB_WORKSPACE/llvm+clang+lld-${{ env.LLVM_VERSION }}-x86_64-windows-msvc-release-mt
 
      - name: Zip LLVM
        run: Compress-Archive -Path $GITHUB_WORKSPACE/llvm+clang+lld-${{ env.LLVM_VERSION }}-x86_64-windows-msvc-release-mt -DestinationPath llvm+clang+lld-${{ env.LLVM_VERSION }}-x86_64-windows-msvc-release-mt.zip
    
      - name: Save Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LLVM
          path: llvm+clang+lld-${{ env.LLVM_VERSION }}-x86_64-windows-msvc-release-mt.zip
          retention-days: 3

