name: CMake
on: [push]

env: 
    LLVM_VERSION: "18.1.8"
    
jobs:
  build_llvm:
    runs-on: windows-2022
    steps:    
      - name: Checkout LLVM
        run: git clone --depth 1 --branch llvmorg-${{LLVM_VERSION}} https://github.com/llvm/llvm-project.git
        
      - name: Configure LLVM
        run: cmake -S llvm-project/llvm -B llvm-project/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DLLVM_USE_CRT_RELEASE=MT -DLLVM_ENABLE_PROJECTS="llvm;clang;lld"

      - name: Build LLVM
        run: cmake --build llvm-project/build --config Release

      - name: Install LLVM
        run: cmake --install llvm-project/build --prefix $GITHUB_WORKSPACE/llvm+clang+lld-${{LLVM_VERSION}}-x86_64-windows-msvc-release-mt
 
      - name: Zip LLVM
        run: Compress-Archive -Path $GITHUB_WORKSPACE/llvm+clang+lld-${{LLVM_VERSION}}-x86_64-windows-msvc-release-mt -DestinationPath llvm+clang+lld-18.1.8-x86_64-windows-msvc-release-mt.zip
    
      - name: Save Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LLVM
          path: llvm+clang+lld-${{LLVM_VERSION}}-x86_64-windows-msvc-release-mt.zip
          retention-days: 3

